# Generated by Django 3.2.25 on 2024-07-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': (('manage_reviews', 'Can manage product reviews'),), 'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='media',
        ),
        migrations.RemoveField(
            model_name='review',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='review',
            name='private_metadata',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
    ]
