# Generated by Django 3.2.25 on 2024-07-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20240713_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['rating'], 'permissions': (('manage_reviews', 'Can manage product reviews'),), 'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
    ]
