# Generated by Django 3.2.25 on 2024-07-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20240717_0331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewmedia',
            options={'ordering': ('pk',)},
        ),
        migrations.RemoveField(
            model_name='reviewmedia',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='reviewmedia',
            name='to_remove',
        ),
    ]
